### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by scimad** [TheDeltaFinders/Shabdakosh#1]
I forked to try to run and maybe work on this project. But there's hardly any documentation. Is it possible to add documentations? Specially for a quick-start and some most important features that are not so self-explanatory?

**Comment by pranphy** [comment]
@scimad I refactored a lot of things from this project, moved around and here we are now. It now only contains one meaningful `.py` source file which is documented. This project now contains doc [`doc/working.md`](https://github.com/TheDeltaFinders/Shabdakosh/blob/master/doc/working.md) showing the intention and general methodology. Feel free to update any of these files and also may be suggest if there is a better way.

**Comment by scimad** [comment]
Thanks. Looks comprehensible. Closing the issue for now.
